### ISSUE TITLE
Is it possible to get the `universeBi` in breadth-first-order?

### ISSUE THREAD

**Issue by LeventErkok** [ndmitchell/uniplate#28]
Is it possible to use `universeBi` to get the output in breadth-first-order? It appears the results are returned in a depth-first fashion. I'm wondering how I can use uniplate to retrieve the universe in a breadth-first fashion. This isn't just idle curiosity, but rather I have a use case where the top-most provenance information stored in a tree of nodes is usually the best choice. I'd appreciate if you can give a pointer as to how I can achieve this.

To illustrate, consider the following toy program:

```haskell
{-# LANGUAGE DeriveDataTypeable #-}

import Data.Data
import Data.Generics.Uniplate.Data

data A = A B Int deriving (Data, Typeable)
data B = B Int   deriving (Data, Typeable)

val :: A
val = A (B 1) 2

ints :: [Int]
ints = universeBi val
```

I get:

```
*Main> ints
[1,2]
```

But this is depth-first, as `1` is obtained from the `B` node. I'd rather get it in the breadth-first order, i.e., receive `[2,1]`. Is this achievable in uniplate?

**Comment by ndmitchell** [comment]
universeBi is built on top of childrenBi and children, so that would be where to look. However, for Uniplate, it doesn't know that B is a layer of constructor but 2 is at the root - things either are an Int, or aren't. As a result, I think you'd need to use SYB, which knows these are different levels of nesting.

**Comment by LeventErkok** [comment]
Thanks!
